"""initial schema

Revision ID: 1b5a99c3cb8a
Revises: 
Create Date: 2026-01-31 14:35:50.970298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5a99c3cb8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('docker_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('preferred_port', sa.String(), nullable=True),
    sa.Column('internal_link_body', sa.Text(), nullable=True),
    sa.Column('external_link_body', sa.Text(), nullable=True),
    sa.Column('is_exposed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docker_id')
    )
    op.create_table('container_ports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('internal_port', sa.Integer(), nullable=False),
    sa.Column('external_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container_widgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('update_interval', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('container_widgets')
    op.drop_table('container_ports')
    op.drop_table('containers')
    # ### end Alembic commands ###
